name: Build zynthbox packaging Docker image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        include:
          - base_image: debian:bookworm
            base_image_tag: debian-bookworm-arm
          - base_image: debian:buster
            base_image_tag: debian-buster-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: probal31
            password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push image with base ${{ matrix.base_image }}
        uses: docker/build-push-action@v5
        with:
            context: .
            file: Dockerfile.zynthbox-packaging
            platforms: linux/arm64
            push: true
            tags: ghcr.io/probal31/zynthbox-packaging:${{ matrix.base_image_tag }}
            build-args: |
              BASE_IMAGE=${{ matrix.base_image }}